In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/manir/Downloads/Car-details-v3 (1).csv")

In [3]:
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [4]:
df=df.drop(["mileage","engine","max_power","torque","name","seats"],axis=1)
df.head()


year  selling_price  km_driven    fuel seller_type transmission  \
0  2014         450000     145500  Diesel  Individual       Manual   
1  2014         370000     120000  Diesel  Individual       Manual   
2  2006         158000     140000  Petrol  Individual       Manual   
3  2010         225000     127000  Diesel  Individual       Manual   
4  2007         130000     120000  Petrol  Individual       Manual   

          owner  
0   First Owner  
1  Second Owner  
2   Third Owner  
3   First Owner  
4   First Owner

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   year           8128 non-null   int64 
 1   selling_price  8128 non-null   int64 
 2   km_driven      8128 non-null   int64 
 3   fuel           8128 non-null   object
 4   seller_type    8128 non-null   object
 5   transmission   8128 non-null   object
 6   owner          8128 non-null   object
dtypes: int64(3), object(4)
memory usage: 444.6+ KB


In [6]:
df.isnull().sum()

year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [7]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [8]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [9]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [10]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [11]:
x=df.iloc[:,:].values
z=pd.DataFrame(x)
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [12]:
df["years_ran"]=2022-df["year"]
df.drop(['year'], axis = 1, inplace= True)
df

selling_price  km_driven    fuel seller_type transmission  \
0            450000     145500  Diesel  Individual       Manual   
1            370000     120000  Diesel  Individual       Manual   
2            158000     140000  Petrol  Individual       Manual   
3            225000     127000  Diesel  Individual       Manual   
4            130000     120000  Petrol  Individual       Manual   
...             ...        ...     ...         ...          ...   
8123         320000     110000  Petrol  Individual       Manual   
8124         135000     119000  Diesel  Individual       Manual   
8125         382000     120000  Diesel  Individual       Manual   
8126         290000      25000  Diesel  Individual       Manual   
8127         290000      25000  Diesel  Individual       Manual   

                     owner  years_ran  
0              First Owner          8  
1             Second Owner          8  
2              Third Owner         16  
3              First Owner         12  
4              First Owner         15  
...                    ...        ...  
8123           First Owner          9  
8124  Fourth & Above Owner         15  
8125           First Owner         13  
8126           First Owner          9  
8127           First Owner          9  

[8128 rows x 7 columns]

In [13]:
X = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [14]:
y= y.reshape(len(y),1)

In [15]:
#OneHotEncoding for 'Fuel Type'.
from sklearn.compose import  ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers= [('encoder' , OneHotEncoder(), [2])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))


In [16]:
#Label Encoding for 'Transmission' 
#Label Encoding for 'Seller-Type'
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,4] = le.fit_transform(X[:,4])
X[:,3] = le.fit_transform(X[:, 3])

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [18]:
X_train

array([[0.0, 1.0, 0.0, ..., 'Manual', 'Second Owner', 8],
       [0.0, 1.0, 0.0, ..., 'Manual', 'Second Owner', 6],
       [0.0, 1.0, 0.0, ..., 'Manual', 'Second Owner', 10],
       ...,
       [0.0, 1.0, 0.0, ..., 'Manual', 'First Owner', 9],
       [0.0, 1.0, 0.0, ..., 'Manual', 'Second Owner', 12],
       [0.0, 1.0, 0.0, ..., 'Manual', 'First Owner', 6]], dtype=object)

In [19]:
X_test

array([[0.0, 1.0, 0.0, ..., 'Manual', 'First Owner', 17],
       [0.0, 1.0, 0.0, ..., 'Manual', 'First Owner', 5],
       [0.0, 1.0, 0.0, ..., 'Manual', 'First Owner', 3],
       ...,
       [1.0, 0.0, 0.0, ..., 'Manual', 'First Owner', 13],
       [0.0, 1.0, 0.0, ..., 'Manual', 'First Owner', 7],
       [0.0, 1.0, 0.0, ..., 'Manual', 'First Owner', 4]], dtype=object)

In [20]:
y_train

array([[420000],
       [675000],
       [570000],
       ...,
       [190000],
       [250000],
       [480000]], dtype=int64)

In [21]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

ValueError: could not convert string to float: 'Manual'

In [ ]:
y_pred = lr.predict(X_test)
result = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)
result

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state = 1)
dtr.fit(X_train, y_train)

y_pred_dtr = dtr.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dtr)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 10, random_state = 1)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred_rf)